"""Action signal definitions for state transitions."""

from enum import Enum


class ActionSignal(str, Enum):
    """
    Action signals that drive state transitions in the agent FST.

    These signals are generated by nodes and consumed by the transition
    function to determine the next state.
    """

    PLAN_COMPLETE = "plan_complete"
    PLAN_ERROR = "plan_error"
    CODE_GENERATED = "code_generated"
    EXECUTION_SUCCESS = "execution_success"
    EXECUTION_ERROR = "execution_error"
    TASK_COMPLETE = "task_complete"
