"""Action signal and node name definitions for the agent graph."""

from enum import Enum


class AgentNode(str, Enum):
    """
    Node names for the agent graph.

    Using an enum ensures consistency across nodes, transitions, and graph definitions.
    """

    PLANNING = "planning"
    CODE_PLANNING = "code_planning"
    CODE_GENERATION = "code_generation"
    CODE_EXECUTION = "code_execution"
    ANSWERING = "answering"


class ActionSignal(str, Enum):
    """
    Action signals that drive state transitions in the agent FST.

    These signals are generated by nodes and consumed by the transition
    function to determine the next state.

    Graph Flow:
    - PLANNING_NODE -> CODE_PLANNING or ANSWERING
    - CODE_PLANNING_NODE -> ITERATE_CURRENT_STEP, PROCEED_TO_NEXT_STEP, or FINALIZE
    - CODE_GENERATION_NODE -> EXECUTE_CODE
    - CODE_EXECUTION_NODE -> CODE_EXECUTED_SUCCESSFULLY or CODE_EXECUTION_FAILED
    """

    # PLANNING_NODE signals
    CODE_PLANNING = "code_planning"  # Task requires code execution, proceed to planning
    GENERAL_ANSWER = "general_answer"  # No code needed, proceed to final answering
    CLARIFICATION = "clarification"  # Task unclear, needs more info before proceeding

    # CODE_PLANNING_NODE signals
    ITERATE_CURRENT_STEP = (
        "iterate_current_step"  # Generate/regenerate code for current step
    )
    PROCEED_TO_NEXT_STEP = "proceed_to_next_step"  # Current step done, plan next step

    # CODE_GENERATION_NODE signals
    EXECUTE_CODE = "execute_code"  # Code generated, ready for execution

    # CODE_EXECUTION_NODE signals
    CODE_EXECUTION_SUCCESS = "code_execution_success"  # Code ran without errors
    CODE_EXECUTION_FAILED = "code_execution_failed"  # Code execution had errors

    # TASK COMPLETION signals
    TASK_COMPLETED = "task_completed"  # Task completed successfully
    TASK_FAILED = "task_failed"  # Unable to complete task successfully

    # ANSWERING_NODE signals
    FINAL_ANSWER = "final_answer"  # Provide final answer to user

    @classmethod
    def from_string(
        cls, signal: str, default: "ActionSignal" = None
    ) -> "ActionSignal | None":
        return cls.__members__.get(signal, default)
